ibexa_connector_quable:
    ### Fill in connection details and you can remove "enabled" field. It will become enabled automatically.
    enabled: false

    # instance_url: ~
    # api_token: ~
    # webhook_secret: ~
