ibexa.discounts.rest:
    resource: '@IbexaDiscountsBundle/Resources/config/routing_rest.yaml'
    prefix: '%ibexa.rest.path_prefix%'

ibexa.discounts.admin:
    resource: '@IbexaDiscountsBundle/Resources/config/routing_admin.yaml'
    defaults:
        siteaccess_group_whitelist: '%admin_group_name%'
