ibexa:
    system:
        default:
            connect:
                client:
                    token: '%env(string:IBEXA_CONNECT_TOKEN)%'
                    host: '%env(string:IBEXA_CONNECT_HOST)%'
                    api_path: '%env(string:IBEXA_CONNECT_API_PATH)%'
