#ibexa:
#    system:
#        default:
#            cdp:
#                # Account number can be obtained from Accounts settings in Ibexa CDP dashboard
#                account_number: 123456
#                data_export:
#                    user_data:
#                        transport: stream_file
#                        stream_file:
#                            # Use Stream ID generated during data import from "stream file" in Data Manager
#                            stream_id: 00000000-00000000-00000000-00000000
#                    content_data:
#                        transport: stream_file
#                        stream_file:
#                            # Use Stream ID generated during data import from "stream file" in Data Manager
#                            stream_id: 00000000-00000000-00000000-00000000
#
#                # You can configure multiple activations here. They have to be of type "Ibexa" in Ibexa DXP dashboard.
#                activations:
#                    -
#                        # Client ID and Secret pair is used to authenticate against Webhook endpoint, make sure it's random and secure
#                        client_id: '%env(CDP_ACTIVATION_CLIENT_ID)%'
#                        client_secret: '%env(CDP_ACTIVATION_CLIENT_SECRET)%'
#                        # Segment Group where CDP data will be imported to
#                        segment_group_identifier: example_segment_group_identifier
#
#ibexa_cdp:
#    data_export:
#        schedule:
#            user:
#                # You can use examples below to build your own data export schedule.
#                # Accepted options can be listed by running `php bin/console ibexa:cdp:stream-user-data --help`
##                # every 15 minutes
##                -
##                    interval: '*/15 * * * *'
##                    options: '--stream-id=00000000-00000000-00000000-00000000 --user-content-type=user --no-draft'
##
##                # every 6 hours
##                -
##                    interval: '0 */6 * * *'
##                    options: '--stream-id=00000000-00000000-00000000-00000000 --user-content-type=user --no-draft'
#
#            content:
#                # You can use examples below to build your own data export schedule.
#                # Accepted options can be listed by running `php bin/console ibexa:cdp:stream-user-data --help`
##                # every 30 minutes
##                -
##                    interval: '*/30 * * * *'
##                    options: '--stream-id=00000000-00000000-00000000-00000000 --content-type=article --no-draft'
##
##                # every 12 hours
##                -
##                    interval: '0 */12 * * *'
##                    options: '--stream-id=00000000-00000000-00000000-00000000 --content-type=article --no-draft'
