#ibexa:
#    system:
#        default:
#            cdp:
#                # Account number can be obtained from Accounts settings in Ibexa CDP dashboard
#                account_number: 123456
#                data_export:
#                    user_data:
#                        transport: stream_file
#                        stream_file:
#                            # Use Stream ID generated during data import from "stream file" in Data Manager
#                            stream_id: 00000000-00000000-00000000-00000000
#                    content_data:
#                        transport: stream_file
#                        stream_file:
#                            # Use Stream ID generated during data import from "stream file" in Data Manager
#                            stream_id: 00000000-00000000-00000000-00000000
#
#                # You can configure multiple activations here. They have to be of type "Ibexa" in Ibexa DXP dashboard.
#                activations:
#                    -
#                        # Client ID and Secret pair is used to authenticate against Webhook endpoint, make sure it's random and secure
#                        client_id: '%env(CDP_ACTIVATION_CLIENT_ID)%'
#                        client_secret: '%env(CDP_ACTIVATION_CLIENT_SECRET)%'
#                        # Segment Group where CDP data will be imported to
#                        segment_group_identifier: example_segment_group_identifier
