ibexa.corporate_account:
    resource: '@IbexaCorporateAccountBundle/Resources/config/routing_admin_ui.yaml'

ibexa.corporate_account.customer_portal:
    resource: '@IbexaCorporateAccountBundle/Resources/config/routing_customer_portal.yaml'
