ibexa.commerce.eshop:
    resource: "@IbexaCommerceEshopBundle/Resources/config/ses_routing.yml"
    prefix: /

ibexa.commerce.tools:
    resource: '@IbexaCommerceToolsBundle/Resources/config/routing.yml'
    prefix: /

ibexa.commerce.translation:
    resource: '@IbexaCommerceTranslationBundle/Resources/config/routing.yml'
    prefix: /

ibexa.commerce.checkout:
    resource: '@IbexaCommerceCheckoutBundle/Resources/config/routing.yaml'
    prefix: /
    
ibexa.commerce.comparison:
    resource: '@IbexaCommerceComparisonBundle/Resources/config/routing.yml'
    prefix: /
    
ibexa.commerce.quick_order:
    resource: '@IbexaCommerceQuickOrderBundle/Resources/config/routing.yml'
    prefix: /
    
ibexa.commerce.search:
    resource: '@IbexaCommerceSearchBundle/Resources/config/routing.yml'
    prefix: /
    
ibexa.commerce.orderhistory:
    resource: '@IbexaCommerceOrderHistoryBundle/Resources/config/routing.yml'
    prefix: /

ibexa.commerce.local_order_management:
    resource: '@IbexaCommerceLocalOrderManagementBundle/Resources/config/routing.yml'
    prefix: /

ibexa.commerce.admin_ui:
    resource: '@IbexaCommerceAdminUiBundle/Resources/config/routing.yaml'

ibexa.commerce.admin_ui.rest:
    resource: '@IbexaCommerceAdminUiBundle/Resources/config/routing_rest.yml'
    prefix:   '%ibexa.rest.path_prefix%'

ibexa.commerce.basket:
    resource: '@IbexaCommerceBasketBundle/Resources/config/routing.yaml'

ibexa.commerce.rest:
    resource: "@IbexaCommerceRestBundle/Resources/config/routing.yaml"
    prefix: '%ibexa.rest.path_prefix%'
