# Enable stateless CSRF protection for forms and logins/logouts
framework:
    form:
        csrf_protection:
            token_id: submit

    csrf_protection:
        stateless_token_ids:
            - submit
            # Stateless CSRF protection is temporary not supported by ibexa/admin-ui
            # - authenticate
            - logout
