framework:
    rate_limiter:
        discount_code_applying:
            policy: 'fixed_window'
            limit: 20
            interval: '1 minute'
            lock_factory: 'lock.discount_code_applying.factory'

    lock:
        discount_code_applying: '%env(IBEXA_LOCK_DSN)%'
