# Base configuration for Elasticsearch
parameters:
    env(ELASTICSEARCH_URL): '%env(ELASTICSEARCH_DSN)%'
    elasticsearch_dsn: "%env(ELASTICSEARCH_URL)%"

ibexa_elasticsearch:
    connections:
        default:
            hosts:
                - "%elasticsearch_dsn%"
