# common parts
parameters:
    ibexa.commerce.site_access.config.search.de.facet_position: left

    ibexa.commerce.site_access.config.core.de.standard_price_factory.fallback_currency: EUR

    ibexa.commerce.site_access.config.core.default.automatic_currency_conversion: true
    ibexa.commerce.site_access.config.core.default.user_menu_bundles: ['IbexaCommerceEshopBundle','IbexaCommerceHistoryBundle']
    ibexa.commerce.site_access.config.price.default.price_export.product_type_filter: [ses_product]
    ibexa.commerce.site_access.config.core.default.breadcrumb_content_label_fields: ['name', 'title']

    ibexa.commerce.site_access.config.seo.default.is_seo_bundle_enabled: false
    ibexa.commerce.site_access.config.core.default.navigation.content:
        types: ["st_module", "folder", "article", "landing_page", "ses_productcatalog"]
        sections: [1, 2, 9]
        enable_priority_zero: false
        #additional field keys for translating navigation node label
        label_fields: ['name', 'title']
        additional_fields: ['intro', 'media', 'alternative_title', 'alternative_intro', 'alternative_image']
    silver_eshop.default.path_prefix_seo: ''

apache_tika:
    path: '%apache_tika_path%'

twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - '@ibexadesign/Forms/form_div_layout.html.twig'

jms_payment_core:
    encryption:
        provider: defuse_php_encryption
        secret: '%env(JMS_PAYMENT_SECRET)%'
        enabled: true

stash:
    caches:
        default:
            drivers:
                - FileSystem
            inMemory: true
            registerDoctrineAdapter: false
            FileSystem:
                keyHashFunction: crc32
