parameters:
    ibexa.commerce.site_access.config.core.default.ses_swiftmailer:
        mailSender: noreply@ibexa.co
        mailReceiver: noreply@ibexa.co
        lostOrderEmailReceiver: noreply@ibexa.co
        contactMailReceiver: noreply@ibexa.co
        cancellationMailReceiver: noreply@ibexa.co
        shopOwnerMailReceiver: noreply@ibexa.co
    ibexa.commerce.eshop.forms.business.default_contact_recipient: noreply@ibexa.co
    ibexa.commerce.eshop.order.sales_contact: noreply@ibexa.co
    ibexa.commerce.eshop.lostorder_email: noreply@ibexa.co
    ibexa.commerce.payment.paypal.receiver.email: noreply@ibexa.co

    ibexa.commerce.core.site_access_group: ezdemo_site_clean_group
    apache_tika_path: '%kernel.project_dir%/bin/tika-app-1.20.jar'

    # commerce solr
#    ibexa.commerce.search.solr.host: '%env(SISO_SEARCH_SOLR_HOST)%'
#    ibexa.commerce.search.solr.port: '%env(SISO_SEARCH_SOLR_PORT)%'
#    ibexa.commerce.search.solr.core: '%env(SISO_SEARCH_SOLR_CORE)%'
#    ibexa.commerce.search.solr.path: '%env(SISO_SEARCH_SOLR_PATH)%'

    one_sky_api_key: my-one-sky-key
    one_sky_secret: my-onesky-password

    ewz_recaptcha_public_key: public_key
    ewz_recaptcha_private_key: private_key
