ibexa.checkout:
    resource: '@IbexaPaymentBundle/Resources/config/routing.yaml'

ibexa.checkout.admin:
    resource: '@IbexaPaymentBundle/Resources/config/routing_admin.yaml'
    defaults:
        siteaccess_group_whitelist: '%admin_group_name%'
